### ISSUE TITLE
Transactions Info along with clustering of addresses

### ISSUE THREAD

**Issue by Anil-Gaihre** [mikispag/bitiodine#14]
Hello,
Can we also obtain the transactions information like sending party/receiving party bitcoin amounts and time stamps along with the cluster information? I need to construct a transaction graph in a project. And how is the clustering done? Are you clustering the input addresses of the individual transactions into 1 address? Are the change addresses are being considered during clustering?

**Comment by mikispag** [comment]
- You would need to code up a custom visitor for that. Use ``dataoutput_finder.rs`` as a base.
- The clustering is done using [Heuristic 1 from my paper](https://www.ifca.ai/fc14/papers/fc14_submission_11.pdf) - multi-input transactions cause input addresses to be clustered together (the spender has the private keys).
- Change address guessing is no longer reliable so it is not used a signal for clustering.
