### ISSUE TITLE
memory allocation of 23400000000 bytes failed

### ISSUE THREAD

**Issue by megolosov** [mikispag/bitiodine#17]
cargo build --release

...
[skip]
...
warning[E0502]: cannot borrow `*slice_inputs_and_outputs` as immutable because it is also borrowed as mutable
   --> src\transactions.rs:138:13
    |
136 |         sha256_hasher1.input(read_slice(
    |                              ---------- mutable borrow later used by call
137 |             &mut slice_inputs_and_outputs,
    |             ----------------------------- mutable borrow occurs here
138 |             slice_inputs_and_outputs.len() - slice.len(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^ immutable borrow occurs here
    |
    = warning: this error has been downgraded to a warning for backwards compatibility with previous releases
    = warning: this represents potential undefined behavior in your code and this warning will become a hard error in the future
    = note: for more information, try `rustc --explain E0729`

warning[E0502]: cannot borrow `*init_slice` as immutable because it is also borrowed as mutable
   --> src\transactions.rs:164:48
    |
164 |             slice: read_slice(&mut init_slice, init_slice.len() - slice.len())?,
    |                    ---------- ---------------  ^^^^^^^^^^ immutable borrow occurs here
    |                    |          |
    |                    |          mutable borrow occurs here
    |                    mutable borrow later used by call
    |
    = warning: this error has been downgraded to a warning for backwards compatibility with previous releases
    = warning: this represents potential undefined behavior in your code and this warning will become a hard error in the future
    = note: for more information, try `rustc --explain E0729`

warning[E0502]: cannot borrow `*init_slice` as immutable because it is also borrowed as mutable
   --> src\transactions.rs:201:48
    |
201 |             slice: read_slice(&mut init_slice, init_slice.len() - slice.len())?,
    |                    ---------- ---------------  ^^^^^^^^^^ immutable borrow occurs here
    |                    |          |
    |                    |          mutable borrow occurs here
    |                    mutable borrow later used by call
    |
    = warning: this error has been downgraded to a warning for backwards compatibility with previous releases
    = warning: this represents potential undefined behavior in your code and this warning will become a hard error in the future
    = note: for more information, try `rustc --explain E0729`

warning[E0502]: cannot borrow `*init_slice` as immutable because it is also borrowed as mutable
   --> src\transactions.rs:226:48
    |
226 |             slice: read_slice(&mut init_slice, init_slice.len() - slice.len())?,
    |                    ---------- ---------------  ^^^^^^^^^^ immutable borrow occurs here
    |                    |          |
    |                    |          mutable borrow occurs here
    |                    mutable borrow later used by call
    |
    = warning: this error has been downgraded to a warning for backwards compatibility with previous releases
    = warning: this represents potential undefined behavior in your code and this warning will become a hard error in the future
    = note: for more information, try `rustc --explain E0729`

    Finished release [optimized] target(s) in 1m 11s

run bitiodine-rust.exe

C:\bitiodine-master\target\release>bitiodine-rust.exe
memory allocation of 23400000000 bytes failed

**Comment by mikispag** [comment]
Try on a machine with more RAM.
