### ISSUE TITLE
generate_transaction_graph.py

### ISSUE THREAD

**Issue by karlbrand** [mikispag/bitiodine#7]
Getting the following error:
```
:~/bitiodine/deploy/grapher$ ./generate_transaction_graph.py
[Errno 2] No such file or directory: 'None.dat'
Traceback (most recent call last):
  File "./generate_transaction_graph.py", line 40, in <module>
    print("Scanning %d transactions, starting from %d." %(amount_txids, min_tx_id))
TypeError: %d format: a number is required, not NoneType
```
Since my attempts failed, might you have a work around suggestion?

**Comment by mikispag** [comment]
Hi,

it looks like your SQLite database is corrupted. This happens because the query fails. There might be so many reasons for this (bitcoind doing weird stuff, etc). Are you running bitcoind, right?

**Comment by karlbrand** [comment]
Hi Miki,

I *was* running it, but terminated it before `./generate_transaction_graph.py` to free up cpu cycles. Should it be running when executing this sript?

**Comment by mikispag** [comment]
Did it complete a blockchain sync?

Anyway, really, it might be anything. I tested with the newest bitcoind some weeks ago and it works to me, but I have not generated the TX graph, just clusters and the C++ server.

**Comment by karlbrand** [comment]
I can't be sure it completed the sync. I'll confirm that it does and report back. Thanks a lot!

**Comment by mikispag** [comment]
I just realized the contributor did not add default argument values (--min-time, --max-time, etc). Please git pull again.

**Comment by karlbrand** [comment]
Thank you Miki. I will try this in in ~12 hrs when my linux box is done with it's current job...
