### ISSUE TITLE
CPU Utilization

### ISSUE THREAD

**Issue by daruosha** [mikispag/bitiodine#8]
Trying to run the "Clusterizer" and graph generators (both transaction and user graphs) on a fully updated block-chain takes extremely long. Looking into CPU and memory usage, reveals the python code which generates the graphs takes advantage of only one CPU core. We're running the scripts on a server with 2 CPUs(Xeon 2690 v2), 768GB RAM and SSD storage. But we never managed to generate graphs properly due to unpractical needed time.

Can you suggest us any solution to boost the running speed and force to use all system resources?

**Comment by mikispag** [comment]
It is working as intended. It is hard to parallelise such a computation, because every step to build clusters depends on the previous one.

Anyway with a much less powerful server I am able to clusterize from scratch in less than 48 hours, and incremental daily updates take less than 15 minutes.

**Comment by daruosha** [comment]
So it seems we have problem in our configuration or code setup. Can you suggest us installation with more details?
