### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by NoahGrumman** [mikispag/bitiodine#9]
Hi, I'm trying to get bitiodine up and running on ubuntu and am getting a seg fault:

info: starting command "sqldump"
info: Dumping the blockchain...
Segmentation fault (core dumped)

Any idea what I could be doing wrong? Thanks!

**Comment by kobigurk** [comment]
Did you ever solve it? I'm getting it too

**Comment by mikispag** [comment]
Hello,

there are so many possible reasons for this, but the culprit is the blockparser. I am no longer actively maintaining BitIodine for the general public, so you might want to run it under gdb and see if that helps!

**Comment by pankajk** [comment]
Is is possible to get the SQL dump, so that, at least we can replicate the results.
